ALTER TABLE CUD.AC_IS_BSS_T
ADD (SIGN_REQ NUMBER(1) DEFAULT 1);

ALTER TABLE CUD.AC_SUBSYSTEM_CERT_BSS_T
ADD (SIGN_REQ NUMBER(1) DEFAULT 1);

ALTER TABLE CUD.GROUP_SYSTEMS_KNL_T
ADD (SIGN_REQ NUMBER(1) DEFAULT 1);